# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(500, 500)
        LoginWindow.setStyleSheet("/* Main Window or Dialog Background */\n"
"QWidget {\n"
"    background-color: #333333; /* Dark grey background */\n"
"    color: yellow; /* Yellow text */\n"
"    font-family: Arial, sans-serif; /* Font style */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"/* Labels (Username, Password) */\n"
"QLabel {\n"
"    color: yellow; /* Yellow text */\n"
"    font-size: 16px; /* Larger font size for labels */\n"
"    font-weight: bold; /* Bold text */\n"
"}\n"
"\n"
"/* Specific Label (label_4) */\n"
"QLabel#label_4 {\n"
"    color: #555555; /* Yellow text */\n"
"    padding: 5px; /* Padding inside the label */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"}\n"
"\n"
"/* Line Edits (Input Fields) */\n"
"QLineEdit {\n"
"    background-color: #444444; /* Darker grey background */\n"
"    color: yellow; /* Yellow text */\n"
"    border: 1px solid yellow; /* Yellow border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 5px; /* Padding inside the input field */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"/* Push Buttons (Login, Register) */\n"
"QPushButton {\n"
"    background-color: yellow; /* Yellow background */\n"
"    color: black; /* Black text */\n"
"    border: 1px solid yellow; /* Yellow border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px; /* Padding inside the button */\n"
"    font-size: 14px; /* Font size */\n"
"    font-weight: bold; /* Bold text */\n"
"}\n"
"\n"
"/* Push Button Hover Effect */\n"
"QPushButton:hover {\n"
"    background-color: #cccc00; /* Darker yellow on hover */\n"
"    border: 1px solid #cccc00; /* Darker yellow border on hover */\n"
"}\n"
"\n"
"/* Push Button Pressed Effect */\n"
"QPushButton:pressed {\n"
"    background-color: #999900; /* Even darker yellow when pressed */\n"
"    border: 1px solid #999900; /* Even darker yellow border when pressed */\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(" color: C4C4C4;\n"
"font-size: 24pt;\n"
"font-weight: bold;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.username_input = QtWidgets.QLineEdit(LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_input.sizePolicy().hasHeightForWidth())
        self.username_input.setSizePolicy(sizePolicy)
        self.username_input.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.username_input.setStyleSheet("color: black;\n"
"background-color: white;")
        self.username_input.setObjectName("username_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.username_input)
        self.label_2 = QtWidgets.QLabel(LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.password_input = QtWidgets.QLineEdit(LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_input.sizePolicy().hasHeightForWidth())
        self.password_input.setSizePolicy(sizePolicy)
        self.password_input.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.password_input.setStyleSheet("color: black;\n"
"background-color: white;")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.password_input)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.register_button = QtWidgets.QPushButton(LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_button.sizePolicy().hasHeightForWidth())
        self.register_button.setSizePolicy(sizePolicy)
        self.register_button.setMinimumSize(QtCore.QSize(120, 40))
        self.register_button.setMaximumSize(QtCore.QSize(500, 16777215))
        self.register_button.setObjectName("register_button")
        self.horizontalLayout_4.addWidget(self.register_button)
        self.login_button = QtWidgets.QPushButton(LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        self.login_button.setMinimumSize(QtCore.QSize(120, 40))
        self.login_button.setMaximumSize(QtCore.QSize(500, 16777215))
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_4.addWidget(self.login_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.logo_label = QtWidgets.QLabel(LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        self.logo_label.setMinimumSize(QtCore.QSize(100, 40))
        self.logo_label.setMaximumSize(QtCore.QSize(1000, 400))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("gui\\../resources/tello.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout.addWidget(self.logo_label)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Dialog"))
        self.label_4.setText(_translate("LoginWindow", "LOGIN"))
        self.label.setText(_translate("LoginWindow", "Username"))
        self.label_2.setText(_translate("LoginWindow", "Password"))
        self.register_button.setText(_translate("LoginWindow", "REGISTER"))
        self.login_button.setText(_translate("LoginWindow", "LOGIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QDialog()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
